# Numpy

NumPy (Numerical Python.) is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# Why Use NumPy?
1. numpy is faster
2. numpy has more bulit-in functions that facilitates data science

In [79]:
#install numpy
!pip install numpy

In [80]:
#import library
import numpy as np
#set version
np.__version__

'1.23.4'

## NumPy Creating Arrays

NumPy is used to work with arrays. The array object in NumPy is called `ndarray` (N-dimensinal array).

We can create a NumPy `ndarray` object by using the `array()` function.

In [81]:
#create your first list
python_list = [1,2,3]
python_list, type(python_list) #value, data type

([1, 2, 3], list)

In [82]:
#convert this list to numpy list
numpy_list = np.array(python_list)
numpy_list, type(numpy_list) #value, data type

(array([1, 2, 3]), numpy.ndarray)

In [83]:
#one theory: one numpy array can only support one type of data
#but python list can support many types of data in one list
my_list = [1,"Hello",True,1.0]
my_numpy = np.array(my_list)
my_numpy #it has change to be string

array(['1', 'Hello', 'True', '1.0'], dtype='<U32')

## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

<img src = './figures/numpy-vector-matrix-3d-matrix.width-1200.jpg' width=600>

### 0-D Arrays

In [84]:
arr_0d = np.array(42)
arr_0d

array(42)

### 1-D Arrays

In [85]:
list_1d = [1, 2, 3, 4, 5, 6, 7, 8]
arr_1d = np.array(list_1d)
arr_1d, arr_1d.shape

(array([1, 2, 3, 4, 5, 6, 7, 8]), (8,))

In [86]:
# arr_1d.reshape(-1,1), arr_1d.reshape(-1,1).shape #This is 2d 

## NumPy Array Indexing

Access Array Elements

<img src = './figures/indexing.jpg' width=200>

In [128]:
arrayX = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arrayX, arrayX.shape

(array([1, 2, 3, 4, 5, 6, 7, 8]), (8,))

In [129]:
#1st way : using index
arrayX[0]

1

In [131]:
#2nd way Slicing - get more than one members
arrayX[3:6]

array([4, 5, 6])

#### Test 1 : 1D Array
<img src = './figures/Test1.jpg' width=300>

In [89]:
#test 
#1. get 6
arr_1d[5], arr_1d[-3]
#2. get 7,8
arr_1d[6:],arr_1d[-3:-1]
#3. get since 5
arr_1d[4:]

array([5, 6, 7, 8])

In [90]:
#3rd way - fancy indexing
arr_1d[2], arr_1d[4]

(3, 5)

In [91]:
#put a list of index you wanna access
arr_1d[[2,4]]

array([3, 5])

### 2-D Arrays

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

<img src = './figures/2darray.jpg' width=300>

In [92]:
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d = np.array(list_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
#format array[row,column]
arr_2d[0,0]

1

## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end]. end is exclude

We can also define the step, like this: [start:end:step].

<img src = './figures/slicing.jpg' width=600>

In [94]:
arrayA = np.array([1,2,3,4,5,6,7,8])
arrayA[0:4], arrayA[6:8]

(array([1, 2, 3, 4]), array([7, 8]))

<img src = './figures/slicing2.jpg' width=500>

In [95]:
arrayA[::2]

array([1, 3, 5, 7])

## Fancy indexing 
Fancy indexing allows you to index an array using another array, a list, or a sequence of integers.

<img src = './figures/fancy.jpg' width=600>

In [96]:
arrayA[[1,4,6]]

array([2, 5, 7])

```[row, column] = [start:end:step, start:end:step]```

In [119]:
arrayB = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arrayB

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<img src = './figures/slicing3.jpg' width=300>

In [126]:
#Red Box
#1st way : #slicing indexing
arr_2d[0, :] 

array([1, 2, 3])

In [127]:
#Yellow Box
#1st way : #slicing indexing
arr_2d[1:,:] 
#2nd way : #fancy indexing
arr_2d[[1,2],:] 
#3rd way : the last two
arr_2d[-2:,:]

array([[4, 5, 6],
       [7, 8, 9]])

#### Test 2 : 2D Array
<img src = './figures/Test2.jpg' width=800>

In [101]:
test2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

#1: get 7,8
test2[1, 2:]
#2: get 2,6,10,14
test2[:,1]
#3: get 7,11
test2[1:3,2]
#4: get 11,12,15,16
test2[2:,2:]
#5: get 4,7,10 - hint: use fancy indexing on both dimensions
test2[[0,1,2],[3,2,1]]
#6: get 16,15,14,13 - hint: use step -1
test2[3, ::-1]
#7: get 5,7,13,15
test2[1::2,0::2]
#7: get 2,4,7,10,12
test2[[0,0,1,2,2],[1,3,2,1,3]]

array([ 2,  4,  7, 10, 12])

### 3-D arrays
<img src = './figures/3darray.jpg' width=900>

In [102]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
arr_3d, arr_3d.shape #channels, rows, columns

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 (3, 2, 3))

## Reshape

### Reshape From 1-D to 2-D
<img src = './figures/1dto2d.jpg' width=400>

In [103]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr = arr.reshape(3, 3)
newarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Reshape From 1-D to 3-D
<img src = './figures/1dto3d.jpg' width=400>

In [104]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

#### Test 3 : Reshape
<img src = './figures/test3.jpg' width=500>

In [105]:
test3 = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
test3, test3.shape

(array([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]),
 (3, 4))

In [106]:
#1 : (3,4) reshape to be (12,)
test3_1 = test3.reshape(12,1)
test3_1, test3_1.shape
#2 : (3,4) reshape to be (2,6)
test3_2 = test3.reshape(2,6)
test3_2, test3_2.shape
#3 : (3,4) reshape to be (6,2)
test3_3 = test3.reshape(6,2)
test3_3, test3_3.shape
#4 : (3,4) reshape to be (4,3)
test3_4 = test3.reshape(4,3)
test3_4, test3_4.shape
#5 : (3,4) reshape to be (12,1)
test3_5 = test3.reshape(12,)
test3_5, test3_5.shape

(array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]), (12,))

### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [107]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Flattening the arrays

In [108]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
newarr

array([1, 2, 3, 4, 5, 6])

## Converting Data Type on Existing Arrays

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [109]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## NumPy Joining Array

If axis is not explicitly passed, it is taken as 0.

##### Concatenate Functions

In [110]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_zero = np.concatenate((arr1, arr2))
print(arr_zero)

[1 2 3 4 5 6]


In [111]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr_zero = np.concatenate((arr1, arr2),axis=0)
arr_one = np.concatenate((arr1, arr2), axis=1)
print('Axis 0 :\n',arr_zero)
print('Axis 1 :\n',arr_one)

Axis 0 :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Axis 1 :
 [[1 2 5 6]
 [3 4 7 8]]


##### Stack Functions
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

In [112]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


Stacking Along Rows

NumPy provides a helper function: hstack() to stack along rows.

In [113]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


Stacking Along Columns

NumPy provides a helper function: vstack()  to stack along columns.

In [114]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [115]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


Creating Filter Directly From Array

In [116]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


### Random Permutations
The NumPy Random module provides two methods for this: shuffle() and permutation().

In [117]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[1 3 2 4 5]


In [118]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[1 5 4 2 3]
