# Numpy

NumPy (Numerical Python.) is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# Why Use NumPy?
1. numpy is faster
2. numpy has more bulit-in functions that facilitates data science

In [2]:
#install numpy
!pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.4'

## NumPy Creating Arrays

In [9]:
#create your first list
python_list = [1,2,3]
python_list, type(python_list)

([1, 2, 3], list)

In [15]:
#convert this list to numpy list
numpy_list = np.array(python_list)
numpy_list, type(numpy_list)

(array([1, 2, 3]), numpy.ndarray)

In [18]:
#one theory: one numpy array can only support one type of data
#but python list can support many types of data in one list
my_list = [1,"Hello",True,1.0]
my_numpy = np.array(my_list)
my_numpy

array(['1', 'Hello', 'True', '1.0'], dtype='<U32')

### 0-D Arrays

In [19]:
arr_0d = np.array(42)
arr_0d

array(42)

### 1-D Arrays

In [20]:
list_1d = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr_1d = np.array(list_1d)
arr_1d, arr_1d.shape

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), (9,))

In [22]:
arr_1d.reshape(-1,1), arr_1d.reshape(-1,1).shape #This is 2d 

(array([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 (9, 1))

## NumPy Array Indexing

Access Array Elements

In [23]:
#1st way : using index
arr_1d[0]

1

In [39]:
#2nd way Slicing - get more than one members
arr_1d[0:3]

array([1, 2, 3])

In [41]:
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
#test 
#1. get 9
arr_1d[8], arr_1d[-1]
#2. get 7,8
arr_1d[6:8],arr_1d[-3:-1]
#3. get since 5
arr_1d[4:]

array([5, 6, 7, 8, 9])

In [54]:
#3rd way - fancy indexing
arr_1d[2],arr_1d[4]

(3, 5)

In [55]:
#put a list of index you wanna access
arr_1d[[2,4]]

array([3, 5])

### 2-D Arrays

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

In [44]:
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d = np.array(list_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
#format array[row,column]
arr_2d[0,0]

1

Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [58]:
#1st way: slicing
arr_2d[1:, :] 

array([[4, 5, 6],
       [7, 8, 9]])

In [59]:
#2nd way : #fancy indexing
arr_2d[[1,2],:] 

array([[4, 5, 6],
       [7, 8, 9]])

In [60]:
#3rd way : the last two
arr_2d[-2:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Exercise
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list  = np.array(x)
# x = np.array(range(1,17))
# x.reshape(4,4)
#1: get 2,6,10,14
#2: get 7,11
#3: get 4,7,10 - hint: use fancy indexing on both dimensions
#4: get 16,15,14,13 - hint: use step -1

### 3-D arrays

In [ ]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr_3d

## Reshape

### Reshape From 1-D to 2-D

In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Reshape From 1-D to 3-D

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Flattening the arrays

In [21]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
newarr

array([1, 2, 3, 4, 5, 6])

## Converting Data Type on Existing Arrays

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [19]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## NumPy Joining Array

If axis is not explicitly passed, it is taken as 0.

##### Concatenate Functions

In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_zero = np.concatenate((arr1, arr2))
print(arr_zero)

[1 2 3 4 5 6]


In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr_zero = np.concatenate((arr1, arr2),axis=0)
arr_one = np.concatenate((arr1, arr2), axis=1)
print('Axis 0 :\n',arr_zero)
print('Axis 1 :\n',arr_one)

Axis 0 :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Axis 1 :
 [[1 2 5 6]
 [3 4 7 8]]


##### Stack Functions
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

In [33]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


Stacking Along Rows

NumPy provides a helper function: hstack() to stack along rows.

In [34]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


Stacking Along Columns

NumPy provides a helper function: vstack()  to stack along columns.

In [36]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [37]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


Creating Filter Directly From Array

In [38]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


### Random Permutations
The NumPy Random module provides two methods for this: shuffle() and permutation().

In [12]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 1 3 4 2]


In [11]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[4 2 5 1 3]
